<div class="table-wrapper">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Size</th>
        <th>Type</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>John</td>
        <td>25</td>
        <td>Developer</td>
      </tr>
      <tr>
        <td>Jane</td>
        <td>30</td>
        <td>Designer</td>
      </tr>
    </tbody>
  </table>
</div>
